### ISSUE TITLE
Possible modification

### ISSUE THREAD

**Issue by EmilJaffal** [bobleesj/cif-filter-copy#2]
After processing CIF files for distance filtering, perhaps no need to exit the histogram for the minimum threshold prompt to pop out.

**Comment by bobleesj** [comment]
Hi Emil, 

Thanks for your suggestion. Now, it has been updated in the latest repository. As some users may not be using graphic user-interface, I have decided not to show a pop-up. Instead, the prompt now appears after the run with a clear message that the histogram.png has been saved in the chosen CIF directory. https://github.com/bobleesj/cif-filter-copy/pull/3

**Comment by EmilJaffal** [comment]
Great, sounds good — thank you! I’ll update it now.
— 
Emil Jaffal
Research Chemist, ICL IP
Fordham University — Class of 2023
